name: Bug Detector

on:
  push:

jobs:
  detect-and-report:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Run code and capture error
        run: |
          python app.py > output.log 2>&1 || true

      - name: Send error to n8n
        run: |
          ERROR=$(cat output.log | head -n 20 | sed 's/"/\\"/g')
          echo "Sending: $ERROR"
          curl -v -X POST https://crayon-employer-wasting.ngrok-free.dev/webhook/bug-detector \
          -H "Content-Type: application/json" \
          -d "{\"error\":\"$ERROR\"}"
